<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="api.mappings.Member.DeleteMemberNegativeTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2025-01-15T13:11:22" hostname="mariana-VirtualBox" time="0.044">
  <properties/>
  <testcase name="deleteMemberSuccess" classname="api.mappings.Member.DeleteMemberNegativeTest" time="0.044">
    <failure message="java.lang.AssertionError: Expected response code to be [404] but was [204]&#10;Expected: is &lt;404&gt;&#10;     but: was &lt;204&gt;" type="java.lang.AssertionError">java.lang.AssertionError: Expected response code to be [404] but was [204]
Expected: is &lt;404&gt;
     but: was &lt;204&gt;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at api.validators.ResponseValidator.assertNotFound(ResponseValidator.java:81)
	at api.mappings.Member.DeleteMemberNegativeTest.deleteMemberSuccess(DeleteMemberNegativeTest.java:29)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:153)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:95)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
	at jdk.proxy1/jdk.proxy1.$Proxy4.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:200)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:132)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:103)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:63)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:121)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[Jan 15, 2025 1:11:22 PM okhttp3.internal.platform.Platform log
INFO: --> DELETE http://localhost:8080/member/45
Jan 15, 2025 1:11:22 PM okhttp3.internal.platform.Platform log
INFO: --> END DELETE
Jan 15, 2025 1:11:22 PM okhttp3.internal.platform.Platform log
INFO: <-- 204 http://localhost:8080/member/45 (10ms)
Jan 15, 2025 1:11:22 PM okhttp3.internal.platform.Platform log
INFO: Date: Wed, 15 Jan 2025 13:11:22 GMT
Jan 15, 2025 1:11:22 PM okhttp3.internal.platform.Platform log
INFO: Keep-Alive: timeout=60
Jan 15, 2025 1:11:22 PM okhttp3.internal.platform.Platform log
INFO: Connection: keep-alive
Jan 15, 2025 1:11:22 PM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP
]]></system-err>
</testsuite>
